### ISSUE TITLE
Export tags in CSV

### ISSUE THREAD

**Issue by igorartzona** [thunderbird/import-export-tools-ng#495]
Hi, big thank's for this extension.

I use ImportExportTools NG for export email data ( usially it's Export All messages in Folder -  Message Index -CSV Format)
Sоme my email have tags, but tags not export :(

Possibly add email tags export in CSV file?

**Comment by cleidigh** [comment]
@igorartzona 
This has been asked about before. It's actually a tricky issue that doesn't have a great answer. The reason is that tags are not stored in the message file mboxes.
To export and be able to re-import and get the tags back into the system would be a difficult addition. At some point I hope Thunderbird will unify this, but for now I cannot really do this.
@cleidigh

**Comment by igorartzona** [comment]
I see, thanks for the answer and your work
