### ISSUE TITLE
Thunderbird 125.0

### ISSUE THREAD

**Issue by Kalinette** [thunderbird/import-export-tools-ng#566]
No longer works under Thunderbird 125.0.

**Comment by DrStrange** [comment]
I don't wish to get into the politics of this here but I have read the statement on https:// thunderbird.tropicbox.com about TB 115.10.2 moving to the ESR channel and freeing the release channel (for TB 125?). I thought ESR was for organisations or people who don't wish to update regularly (which is the case for Firefox)? When TB 115 was introduced automatic updating was not available so I was downloading each new update manually. Now when I installed TB 115.10.2 it has suddenly updated itself to TB 125 which as stated is a beta and causes IET NG to stop working (unless you increase  strict_max_version to >=125 and test for issues). I don't think this version increase is expected behaviour. Would re-installing TB 115.10.2 over TB 125 with `-allow-downgrade` parameter prevent it updating to TB 125 or would the same thing happen again?

**Comment by cleidigh** [comment]
@Kalinette 
I am close to a first beta, so far main functions look good.
@cleidigh

**Comment by cleidigh** [comment]
@Kalinette 
All
I have posted the first beta for Thunderbird v128 support 
- #575 

@cleidigh

**Comment by cleidigh** [comment]
@Kalinette 
Have you tried the beta?
@cleidigh
